# Каталог продуктов Biolar Organics — 22 SKU

PRODUCTS = {
    "iron_optiferrol": {
        "id": "iron_optiferrol",
        "name": "Iron OptiFerrol",
        "tagline": "Липосомальное железо — без побочек ЖКТ",
        "benefits": ["Устраняет усталость и слабость", "Бисглицинат в 3-4 раза лучше обычного", "Восстанавливает уровень гемоглобина", "Поддержка волос и кожи"],
        "emoji": "🔴",
        "duration_days": 30,
        "wb_url":   "https://www.wildberries.ru/catalog/1103571089/detail.aspx",
        "ozon_url": "https://ozon.ru/product/4132134811",
    },
    "progesterone_control": {
        "id": "progesterone_control",
        "name": "Прогестерон Контроль",
        "tagline": "ПМС, прогестерон и перименопауза",
        "benefits": ["Снижение симптомов ПМС", "Нормализация цикла", "Витекс + активный B6 (P5P)", "Детоксикация эстрогенов"],
        "emoji": "🌸",
        "duration_days": 30,
        "wb_url":   "https://www.wildberries.ru/catalog/812124423/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3260660527",
    },
    "vitamin_c_lipovit_90": {
        "id": "vitamin_c_lipovit_90",
        "name": "Витамин С Lipovit — 90 капсул",
        "tagline": "Липосомальный витамин C — максимальное усвоение",
        "benefits": ["Липосомальная форма +50% к усвоению", "Антиоксидантная защита", "Иммунитет и синтез коллагена", "Запас на 3 месяца"],
        "emoji": "🍋",
        "duration_days": 90,
        "wb_url":   "https://www.wildberries.ru/catalog/959637833/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3266530538",
    },
    "vitamin_c_lipovit_60": {
        "id": "vitamin_c_lipovit_60",
        "name": "Витамин С Lipovit — 60 капсул",
        "tagline": "Липосомальный витамин C — максимальное усвоение",
        "benefits": ["Липосомальная форма +50% к усвоению", "Антиоксидантная защита", "Иммунитет и синтез коллагена", "Запас на 2 месяца"],
        "emoji": "🍋",
        "duration_days": 60,
        "wb_url":   "https://www.wildberries.ru/catalog/959610501/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3260672306",
    },
    "vitamin_c_factor": {
        "id": "vitamin_c_factor",
        "name": "Витамин С Factor C",
        "tagline": "Двухэтапное действие — утром и вечером",
        "benefits": ["Двухфазное высвобождение", "Антиоксидант + иммунитет", "Синтез коллагена", "Поддержка надпочечников"],
        "emoji": "🍊",
        "duration_days": 30,
        "wb_url":   "https://www.wildberries.ru/catalog/959628596/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3260651473",
    },
    "immular_activator": {
        "id": "immular_activator",
        "name": "IMMULAR Activator",
        "tagline": "Мощный иммунный комплекс",
        "benefits": ["Эхинацея + бузина + элеутерококк", "Защита от ОРВИ и вирусов", "Восстановление после болезни", "Антиоксидантная защита"],
        "emoji": "🛡",
        "duration_days": 30,
        "wb_url":   "https://www.wildberries.ru/catalog/959605999/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3266524229",
    },
    "immular_booster": {
        "id": "immular_booster",
        "name": "IMMULAR Booster",
        "tagline": "Иммунный бустер для быстрого результата",
        "benefits": ["Быстрое усиление иммунитета", "Поддержка в сезон простуд", "Комплекс природных иммуностимуляторов", "Совместим с Activator"],
        "emoji": "⚡",
        "duration_days": 30,
        "wb_url":   "https://www.wildberries.ru/catalog/959580946/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3266525466",
    },
    "immular_control": {
        "id": "immular_control",
        "name": "IMMULAR Control",
        "tagline": "Контроль и баланс иммунной системы",
        "benefits": ["Регуляция иммунного ответа", "Поддержка при аутоиммунных состояниях", "Длительный курс поддержки", "Противовоспалительный эффект"],
        "emoji": "🔵",
        "duration_days": 60,
        "wb_url":   "https://www.wildberries.ru/catalog/959576065/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3266526585",
    },
    "d3_4000": {
        "id": "d3_4000",
        "name": "Витамин Д3 4000 МЕ",
        "tagline": "Высокодозный D3 для восполнения дефицита",
        "benefits": ["4000 МЕ — терапевтическая дозировка", "Иммунитет и гормональный фон", "Кости, мышцы и настроение", "Для регионов с низкой инсоляцией"],
        "emoji": "☀️",
        "duration_days": 60,
        "wb_url":   "https://www.wildberries.ru/catalog/812051867/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3260654603",
    },
    "d3_7elements": {
        "id": "d3_7elements",
        "name": "Витамин Д3 2000 МЕ + 7 элементов",
        "tagline": "Иммунитет, сосуды и метаболизм",
        "benefits": ["D3 2000 МЕ + витамины C, K2, группы B", "Мощная иммунная поддержка", "Защита сосудов и костей", "Здоровье кожи и антиэйдж"],
        "emoji": "🟠",
        "duration_days": 60,
        "wb_url":   "https://www.wildberries.ru/catalog/959626577/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3260653002",
    },
    "d3_k2_liposomal": {
        "id": "d3_k2_liposomal",
        "name": "Липосомальный Д3+К2",
        "tagline": "4000 МЕ D3 с K2 — максимальное усвоение",
        "benefits": ["Липосомальная форма +50% усвоения", "K2 (MK-7) направляет кальций в кости", "Защита сосудов от кальцификации", "Иммунитет и репродуктивная функция"],
        "emoji": "🌟",
        "duration_days": 60,
        "wb_url":   "https://www.wildberries.ru/catalog/812129641/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3260661849",
    },
    "neuro_complex": {
        "id": "neuro_complex",
        "name": "Нейро Комплекс",
        "tagline": "Мозг, фокус и защита от выгорания",
        "benefits": ["Гинкго билоба + L-теанин", "Концентрация без перевозбуждения", "Снижение стресса и тревожности", "Защита от хронического выгорания"],
        "emoji": "🧠",
        "duration_days": 30,
        "wb_url":   "https://www.wildberries.ru/catalog/959636021/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3260643952",
    },
    "calcium_7essential": {
        "id": "calcium_7essential",
        "name": "Кальций 7 Essential",
        "tagline": "Кальций + 7 синергичных элементов",
        "benefits": ["Прочность костей и зубов", "Профилактика остеопороза", "Поддержка мышц и нервной системы", "Комплексная формула усвоения"],
        "emoji": "🦴",
        "duration_days": 30,
        "wb_url":   "https://www.wildberries.ru/catalog/813128593/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3266531621",
    },
    "hormone_balance": {
        "id": "hormone_balance",
        "name": "Гормон Баланс — 90 капсул",
        "tagline": "СПКЯ, нерегулярный цикл, гормональный баланс",
        "benefits": ["Инозитол MYO+DCI соотношение 40:1", "Снижение андрогенов при СПКЯ", "Нормализация цикла и овуляции", "Инсулинорезистентность"],
        "emoji": "🌺",
        "duration_days": 90,
        "wb_url":   "https://www.wildberries.ru/catalog/959617408/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3260665822",
    },
    "chromium_4essential": {
        "id": "chromium_4essential",
        "name": "Хром 4 Essential",
        "tagline": "Контроль сахара и тяги к сладкому",
        "benefits": ["Регуляция уровня глюкозы", "Снижение тяги к сладкому", "Поддержка похудения", "Улучшение чувствительности к инсулину"],
        "emoji": "💎",
        "duration_days": 30,
        "wb_url":   "https://www.wildberries.ru/catalog/813131657/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3267158912",
    },
    "magnesium_4elements": {
        "id": "magnesium_4elements",
        "name": "Магний 4 Elements",
        "tagline": "Глубокое расслабление, фокус и сон",
        "benefits": ["Снижение стресса и тревожности", "Глубокий и качественный сон", "Улучшение фокуса и ясности ума", "L-теанин + витамины B2, B6, D3"],
        "emoji": "🟣",
        "duration_days": 30,
        "wb_url":   "https://www.wildberries.ru/catalog/959608801/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3260678721",
    },
    "vitamin_c_faster": {
        "id": "vitamin_c_faster",
        "name": "Витамин С Faster C",
        "tagline": "Быстрое усвоение — янтарная кислота + рутин",
        "benefits": ["Быстродействующая формула", "Антиоксидант + иммунитет", "Синтез коллагена", "Янтарная кислота усиливает эффект"],
        "emoji": "🍊",
        "duration_days": 30,
        "wb_url":   "https://www.wildberries.ru/catalog/959517018/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3266527940",
    },
    "thyrosel": {
        "id": "thyrosel",
        "name": "ThyroSel",
        "tagline": "Минималистичная формула: Se + Zn + Myo",
        "benefits": ["Селен + цинк — основа щитовидки", "Мио-инозитол 600 мг", "Чистая формула без лишнего", "Для тех кто уже принимает лечение"],
        "emoji": "🔵",
        "duration_days": 60,
        "wb_url":   "https://www.wildberries.ru/catalog/812121030/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3260655716",
    },
    "inositol_myo_dchiro": {
        "id": "inositol_myo_dchiro",
        "name": "Гормон Баланс — 75 капсул",
        "tagline": "СПКЯ, овуляция и фертильность",
        "benefits": ["Соотношение MYO:DCI = 40:1", "Улучшение овуляции и фертильности", "Подготовка к ЭКО", "Регуляция инсулина"],
        "emoji": "🌿",
        "duration_days": 75,
        "wb_url":   "https://www.wildberries.ru/catalog/812108141/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3260655730",
    },
    "vitamin_c_pecto": {
        "id": "vitamin_c_pecto",
        "name": "Витамин С Pecto C",
        "tagline": "12-часовое замедленное высвобождение",
        "benefits": ["Пролонгированное действие 12 часов", "Мягкое воздействие на ЖКТ", "Стабильный уровень витамина C", "Пектин замедляет всасывание"],
        "emoji": "🍑",
        "duration_days": 30,
        "wb_url":   "https://www.wildberries.ru/catalog/959632617/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3260650749",
    },
    "zinc_2elements": {
        "id": "zinc_2elements",
        "name": "Цинк 2 Elements (ZincBioCu®)",
        "tagline": "Цинк + медь для кожи, волос и иммунитета",
        "benefits": ["Пиколинат цинка — высокое усвоение", "Здоровье кожи и волос", "Иммунитет и заживление", "Медь предотвращает дисбаланс"],
        "emoji": "⚡",
        "duration_days": 30,
        "wb_url":   "https://www.wildberries.ru/catalog/959620722/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3260664687",
    },
    "thyroid_support": {
        "id": "thyroid_support",
        "name": "Thyroid Support",
        "tagline": "Полный комплекс для щитовидной железы",
        "benefits": ["Гипотиреоз и АИТ", "Селен + цинк + йод + магний", "Активные формы B-витаминов (P5P, метилфолат)", "Поддержка конверсии Т4 → Т3"],
        "emoji": "🦋",
        "duration_days": 60,
        "wb_url":   "https://www.wildberries.ru/catalog/959615578/detail.aspx",
        "ozon_url": "https://ozon.ru/product/3260669524",
    },
}


# --- Квиз ---

QUIZ_QUESTIONS = {
    "goal": {
        "id": "goal",
        "text": "Какая твоя главная цель?",
        "options": [
            {"id": "energy",    "text": "⚡ Энергия и восстановление"},
            {"id": "sleep",     "text": "🌙 Сон и снижение стресса"},
            {"id": "immunity",  "text": "🛡 Укрепить иммунитет"},
            {"id": "hormones",  "text": "🌸 Женское здоровье / цикл"},
            {"id": "thyroid",   "text": "🦋 Щитовидная железа"},
            {"id": "brain",     "text": "🧠 Мозг и фокус"},
            {"id": "beauty",    "text": "✨ Красота (кожа, волосы, ногти)"},
            {"id": "weight",    "text": "⚖️ Контроль веса и сахара"},
        ],
    },
    "energy_detail": {
        "id": "energy_detail",
        "text": "Что беспокоит больше всего?",
        "options": [
            {"id": "fatigue",   "text": "😴 Постоянная усталость и слабость"},
            {"id": "anemia",    "text": "🩸 Были низкие показатели железа / анемия"},
            {"id": "general",   "text": "🔋 Общая нехватка сил и энергии"},
        ],
    },
    "immunity_detail": {
        "id": "immunity_detail",
        "text": "Уточни задачу:",
        "options": [
            {"id": "often",     "text": "🤧 Часто болею ОРВИ (3+ раза в год)"},
            {"id": "d3",        "text": "☀️ Мало солнца, подозреваю дефицит D3"},
            {"id": "general",   "text": "💪 Хочу общее укрепление иммунитета"},
        ],
    },
    "hormones_detail": {
        "id": "hormones_detail",
        "text": "Что именно беспокоит?",
        "options": [
            {"id": "pms",       "text": "😣 ПМС — раздражительность, боли, перепады настроения"},
            {"id": "pcos",      "text": "🔄 СПКЯ или нерегулярный цикл"},
            {"id": "thyroid_f", "text": "🦋 Проблемы со щитовидкой"},
        ],
    },
    "thyroid_detail": {
        "id": "thyroid_detail",
        "text": "Какой вариант тебе подходит?",
        "options": [
            {"id": "full",      "text": "🔬 Хочу полный комплекс поддержки"},
            {"id": "minimal",   "text": "✅ Нужна минималистичная формула (уже принимаю лечение)"},
        ],
    },
}

FOLLOW_UP = {
    "energy":   "energy_detail",
    "sleep":    None,
    "immunity": "immunity_detail",
    "hormones": "hormones_detail",
    "thyroid":  "thyroid_detail",
    "brain":    None,
    "beauty":   None,
    "weight":   None,
}

QUIZ_RESULTS = {
    ("energy", "fatigue"):      ["iron_optiferrol", "d3_7elements"],
    ("energy", "anemia"):       ["iron_optiferrol"],
    ("energy", "general"):      ["d3_7elements", "magnesium_4elements"],
    ("sleep",):                 ["magnesium_4elements", "neuro_complex"],
    ("immunity", "often"):      ["immular_activator", "vitamin_c_faster"],
    ("immunity", "d3"):         ["d3_k2_liposomal"],
    ("immunity", "general"):    ["immular_activator", "d3_7elements"],
    ("hormones", "pms"):        ["progesterone_control"],
    ("hormones", "pcos"):       ["hormone_balance", "inositol_myo_dchiro"],
    ("hormones", "thyroid_f"):  ["thyroid_support"],
    ("thyroid", "full"):        ["thyroid_support"],
    ("thyroid", "minimal"):     ["thyrosel"],
    ("brain",):                 ["neuro_complex", "magnesium_4elements"],
    ("beauty",):                ["zinc_2elements", "d3_7elements", "iron_optiferrol"],
    ("weight",):                ["chromium_4essential", "magnesium_4elements"],
}


def get_quiz_result(goal: str, detail: str = None) -> list[dict]:
    key = (goal, detail) if detail else (goal,)
    product_ids = QUIZ_RESULTS.get(key, [])
    return [PRODUCTS[pid] for pid in product_ids if pid in PRODUCTS]


def get_follow_up_question(goal: str) -> dict | None:
    key = FOLLOW_UP.get(goal)
    return QUIZ_QUESTIONS.get(key) if key else None
